// <auto-generated />
using System;
using MSP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MSP.Data.Migrations
{
    [DbContext(typeof(MSPContext))]
    [Migration("20260127161927_crud systems settings")]
    partial class crudsystemssettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MSP.Domain.Entities.MSPSystemSettings", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("DTBegin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DTEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DTUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SettingKey");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("MSPSystemSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
