// <auto-generated />
using System;
using MSP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MSP.Data.Migrations
{
    [DbContext(typeof(MSPContext))]
    [Migration("20260205174806_set IsUnique in person.Login")]
    partial class setIsUniqueinpersonLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MSP.Domain.Entities.MSPPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<DateTime?>("DTBegin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DTEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DTUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Passworld")
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("MSPPerson");
                });

            modelBuilder.Entity("MSP.Domain.Entities.MSPSystemSettings", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DTBegin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DTEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DTUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SettingValue")
                        .HasColumnType("text");

                    b.HasKey("SettingKey");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("MSPSystemSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
